repos:
-   repo: local
    hooks:
      - id: check-task-frontmatter
        name: Check agentydragon task frontmatter
        entry: python3 agentydragon/tools/check_task_frontmatter.py
        language: python
        additional_dependencies: [PyYAML]
        files: ^agentydragon/tasks/[0-9]{2}-.*\.md$