repos:
-   repo: local
    hooks:
      - id: check-task-frontmatter
        name: Check agentydragon task frontmatter
        entry: python3 agentydragon/tools/check_task_frontmatter.py
        language: python
        additional_dependencies: [PyYAML, toml, pydantic]
        files: ^agentydragon/tasks/[0-9]{2}-.*\.md$
      - id: cargo-build
        name: Check Rust workspace builds
        entry: bash -lc 'cd codex-rs && cargo build --workspace --locked'
        language: system
        pass_filenames: false
        require_serial: true
