repos:
-   repo: local
    hooks:
      - id: check-tasks
        name: Run all task-directory validation checks
        entry: python3 agentydragon/tools/check_tasks.py
        language: python
        additional_dependencies: [PyYAML, toml, pydantic]
        files: ^agentydragon/tasks/.*
      - id: cargo-build
        name: Check Rust workspace and linux-sandbox compile
        entry: bash -lc 'cd codex-rs && RUSTFLAGS="-D warnings" cargo build --workspace --locked --all-targets && cargo build -p codex-linux-sandbox --locked --all-targets'
        language: system
        pass_filenames: false
        require_serial: true
