[package]
name = "codex-session"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "codex-session"
path = "src/main.rs"

[lib]
name = "codex_session"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
codex-core = { path = "../core" }
tokio = { version = "1", features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# --- additions for PTY/TUI support ---
bytes = "1.5"

# Raw terminal handling when attaching to TUI sessions
crossterm = "0.27"

# PTY helpers (unix only)

# new dependencies for session management
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
dirs = "5"
sysinfo = "0.29"
tabwriter = "1.3"
serde_yaml = "0.9"
names = "0.14"

# unix-only process helpers
nix = { version = "0.27", default-features = false, features = ["process", "signal", "term", "fs"] }

# Re-use the codex-exec library for its CLI definition
codex_exec = { package = "codex-exec", path = "../exec" }
codex_repl = { package = "codex-repl", path = "../repl" }
codex_tui = { package = "codex-tui", path = "../tui" }

[dev-dependencies]
tempfile = "3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
