[package]
name = "codex-exec"
version = "0.1.0"
edition = "2021"

# A short description of this crate that will be shown on crates.io and when
# someone runs `cargo search`. Keep it concise yet informative.
description = "Headless command-line interface for running the Codex agent in a Git repository. Streams events, executes sandboxed shell commands, and prints colorized logs – ideal for automation, scripting and CI pipelines."

[[bin]]
name = "codex-exec"
path = "src/main.rs"

[lib]
name = "codex_exec"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
chrono = "0.4.40"
clap = { version = "4", features = ["derive"] }
codex-core = { path = "../core", features = ["cli"] }
owo-colors = { version = "4.2.0", features = ["supports-colors"] }
shlex = "1.3.0"
tokio = { version = "1", features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
