[package]
name = "codex-login"
version = { workspace = true }
edition = "2024"

[lints]
workspace = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
open = "5"
url = "2"
base64 = "0.22"
sha2 = "0.10"
rand = "0.8"
http-body-util = "0.1"
